### PR TITLE
make this repo available on windows.

### PR DESCRIPTION
**Pull request by panhaoyu**
Hello, there's some import errors and the test case does not work.
I fix the import errors, but not fix the test cases.
Hope you can update your test cases.
Best wishes!

### CODE REVIEW

**Comment by jlu5** [comment]
Thanks for your interest in icoextract!

So it seems that installing command line apps in setuptools using [`scripts`](https://github.com/jlu5/icoextract/blob/master/setup.py#L52) wasn't as portable as I thought. Applying this patch would make Windows installations work but break *nix systems.

It looks like the proper solution is to use [`entry_points`](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) instead and refactor the scripts to be functions within a module. I'll work on this bit of refactoring.

**Comment by jlu5** [comment]
Can you check again with the latest git master? If you run these commands to install icoextract and dependencies:

```
pip install -r requirements.txt
python setup.py install
```

Then setuptools will automatically create `icoextract.exe` and `icolist.exe` inside your Python scripts folder (e.g. `C:\Users\<your username>\AppData\Local\Programs\Python\Python38\Scripts`). Assuming this is added to your PATH, you should be able to run the scripts directly by name: e.g. `icoextract --help`

**Comment by panhaoyu** [comment]
I'm sorry but the problem is not about setuptools. In python world, I think it's common to use pip to install a program, but this repo need to clone and run mannually.

**Comment by panhaoyu** [comment]
I jus tried and it met a PermissionError.

```text
C:\Users\wolf\Desktop\icoextract>python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\Python38\\Lib\\site-packages\\test-easy-install-16644.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\Python38\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by panhaoyu** [comment]
I install with admin account and it works well, nice work, and if we can install it from pypi, I think it could be better. Or provide a command like `git install git+https://github.com/jlu5/icoextract` is also great. Clone a repo and install it with setup is a little difficult for new programmers like me.

**Comment by jlu5** [comment]
I'll upload things to pypi soon :)

**Comment by jlu5** [comment]
The PyPI package is published at https://test.pypi.org/project/icoextract/
The included scripts should now work on both Windows and Linux.

**Pull request closed without merging**
