### PR TITLE
exe-thumbnailer: always resize png to target size

### PR DESCRIPTION
**Pull request by Boria138**

### CODE REVIEW

**Comment by Boria138** [comment]
@vinyanalista doc_upload is broken

**Comment by jlu5** [comment]
Can you provide some context as to why resizing icons up is helpful?

**Comment by Boria138** [comment]
> Can you provide some context as to why resizing icons up is helpful?

I use icoextract in my program to extract icons from exe files, for a beautiful display of icons in the interface their size is locked at 128 pixels anything smaller is not displayed because it looks too small, but sometimes there are icons larger than 48 pixels in the exe is simply not, so I thought it would be logical to change the icon resolution to that specified in -s

**Comment by jlu5** [comment]
So for context, exe-thumbnailer implements the [Freedesktop.org thumbnail specification](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html) - i.e. thumbnailing exe files for Linux file managers. I didn't originally design it to be a general purpose image exporter, but there is probably room for making it more flexible.

Specifically, the thumbnailer spec defines two sizes that we're interested in exporting: a "normal" icon no larger than 128x128 and a "large" icon no larger than 256x256. It doesn't explicitly say what to do when the source file is smaller than both of these, so I leave programs which only have smaller icons as is. In practice, it seems some file managers (Caja, Nautilus) will then scale up these small icons, while others (Thunar) will show a small icon in a large box. I'm not sure if either is strictly better, but IIRC the latter is how Windows does it as well.

Given all that, I'm not sure unconditionally upscaling images is a good thing. It may work better for your use case, but not necessarily in a file manager. Maybe a --force-resize option would be better?

**Comment by jlu5** [comment]
As an aside, I've noticed another bug in the current thumbnailer. It's possible for an .exe file to have icon sizes ~~larger than~~ between 128x128 and 256x256, so the thumbnailer may create oversized outputs... Whoops

I will fix CI separately so it doesn't run doc-upload for pull requests, and only the master branch.

**Comment by Boria138** [comment]
> Maybe a --force-resize option would be better?

Ok I'll rewrite the code to work with the --force-resize argument

**Pull request closed without merging**
