### PR TITLE
Moved the long_desc and python version check to setup.cfg and added a…

### PR DESCRIPTION
**Pull request by jgstew**
… GitHub Action to test builds.

----

I also tried and failed to move the version info from `setup.py` to `setup.cfg`, so I didn't include that in this pull request.

When I moved the version to `setup.cfg` using attrib: it actually worked for `python3 setup.py --version` but whenever I did `python3 -m build` it failed to build, which was very strange. I was trying to remove the use of `exec(f.read())` but for some reason not having it caused other problems with the build process that I really don't understand how to unpack.

### CODE REVIEW

**Comment by jlu5** [comment]
Hi, I'll check the setup process shortly, but no need for GitHub Actions. There's already a CI server hooked up to this repo

**Comment by jgstew** [comment]
I can remove the GitHub Action, though it is not a bad thing to have. It is just testing to make sure the build process works correctly, and it is free to run. I also like it because I can easily run the github action locally using `act -j test_build` which will do so in docker containers automatically for me.

I didn't even realize you had another CI pipeline until I submitted the first pull request.

**Comment by jlu5** [comment]
Please keep it to one CI server at a time. Otherwise we're duplicating code and making build status harder to keep track of.

**Comment by jgstew** [comment]
I removed the GitHub action CI test_build.

It was very simple and should never really need changed over time, but you are right that your CI should be > it, so it is kind of redundant.

It really only makes sense if you want to move all of the CI over to GitHub actions over time.

**Comment by jgstew** [comment]
Also, here is an example project that uses both Setup.cfg and Setup.py in a similar way that I was trying to achieve for this project:

https://github.com/jgstew/besapi/blob/master/setup.cfg

The only reason to do this was to remove the need for:

https://github.com/jlu5/icoextract/blob/1e8e3919b80829d6893f83f836266f3419633192/setup.py#L9-L10

but for whatever reason, adding:

`version = attr: icoextract.version.__version__`

Like this:

https://github.com/jgstew/besapi/blob/ab7a3b5a5617acf274082dd135af48b56c562bc0/setup.cfg#L4

caused it to no longer build.

What is really weird is this was the build error:

```
File "/mnt/c/Users/james/Documents/_Code/icoextract/icoextract/__init__.py", line 11, in <module>
    import pefile
ModuleNotFoundError: No module named 'pefile'
```

Which is weird because `pefile` is definitely present, otherwise it wouldn't build correctly before I made this change.

**Comment by jgstew** [comment]
Interesting, I see from your CI thing, it runs `python setup.py install` to do the build. I was running `python -m build` instead. I don't think that makes a difference though since it did work for me before I made the change that I ended up removing.

**Comment by jlu5** [comment]
I'm not sure honestly, this is the first time I'm reading about setup.cfg or python -m build. The thing with Python packaging is there's a gazillion ways to accomplish one task, like the [version loading](https://packaging.python.org/guides/single-sourcing-package-version/) for example..

**Pull request closed without merging**
